In [1]:
import numpy as np

### арифтметичні операції над Нампай масивами

In [2]:
rm = np.random.randint(0, 10, size=(3,3))
im = np.identity(3)

print(f"""
Початкова рандомна матриця: 
{rm}
Початкова матриця ідентичності: 
{im}
Арифметичні операції які здйснюються поелементно:
Додавання
{rm + im + 1} 
Віднімання
{rm - im + 5}
Множення і решта операцій (складні вирази)
{(rm - 5) * (im + 5) }


{rm[rm >= 5]}
""")


Початкова рандомна матриця: 
[[9 5 8]
 [7 7 4]
 [8 4 1]]
Початкова матриця ідентичності: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Арифметичні операції які здйснюються поелементно:
Додавання
[[11.  6.  9.]
 [ 8.  9.  5.]
 [ 9.  5.  3.]] 
Віднімання
[[13. 10. 13.]
 [12. 11.  9.]
 [13.  9.  5.]]
Множення і решта операцій (складні вирази)
[[ 24.   0.  15.]
 [ 10.  12.  -5.]
 [ 15.  -5. -24.]]


[9 5 8 7 7 8]



### трохи про вищу математику

In [3]:
# навіть якщо ми не знаємо як рахувати детернінант матриці, Пайтон знає
np.linalg.det(rm)

np.float64(-180.0)

In [4]:
RM = np.matrix(rm)

RM

matrix([[9, 5, 8],
        [7, 7, 4],
        [8, 4, 1]])

In [5]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.matrix(A)
MB = np.matrix(B)

print(f"""Тут масиви перетворені на матриці і далі перемножуються:\n 
{MA * MB} 
Так само  як і:
{MA.dot(MB)}
""")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]] 
Так само  як і:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]



### Пробуємо вирівнювати масиви

In [6]:
print(rm.shape, rm)

a1 = np.array([1, 2, 3])
print(a1.shape, a1)

rm + a1

a2 = np.array([ [1], [2], [3] ])
print(a2.shape, a2)

rm + a2

A2 = a2[np.newaxis, :]
print(A2.shape)

rm + A2

(3, 3) [[9 5 8]
 [7 7 4]
 [8 4 1]]
(3,) [1 2 3]
(3, 1) [[1]
 [2]
 [3]]
(1, 3, 1)


array([[[10,  6,  9],
        [ 9,  9,  6],
        [11,  7,  4]]])