# Операції над масивами
> хоча базово всі дані інтерпретуються як масиви, можливо працювавти з двовимірними масивами як алгебраїчними матрицями.

In [47]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

> згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [48]:
l = (3, 3)

O = np.ones(l)
R = np.random.random(l)
Z = np.zeros(l)
C = np.arange(l[0])

print(f"""
Віднімання:\n {C - (O + 10)}
Множення:\n {O * R}
Ділення:\n {R / C}
Степінь:\n {C ** Z}
Поріняння:\n {R > 0.5}
Ділення на 0:\n {O / Z}
""")
homework("""
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
""")
print("Завдання 1:")
eye_matrix = np.eye(3)
print(f"Матриця одинична (eye):\n{eye_matrix}")

comparison = eye_matrix == 1
print(f"Порівняння на наявність 1 у матриці:\n{comparison}")

print("\nЗавдання 2:")
ones_matrix = np.ones((3, 3))
print(f"Матриця з одиниць:\n{ones_matrix}")

result = ones_matrix - np.eye(3)
print(f"Результат віднімання матриці eye від ones:\n{result}")


Віднімання:
 [[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]
Множення:
 [[0.44563544 0.47805774 0.7310425 ]
 [0.15915317 0.86184478 0.82129518]
 [0.01216089 0.34238794 0.96372031]]
Ділення:
 [[       inf 0.47805774 0.36552125]
 [       inf 0.86184478 0.41064759]
 [       inf 0.34238794 0.48186016]]
Степінь:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Поріняння:
 [[False False  True]
 [False  True  True]
 [False False  True]]
Ділення на 0:
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


>>>>> 
- Створіть власну матрицю за допомогою методу eye та виконайте порівняння на наявність 1.
- Створіть матрицю ones та відніміть від неї матрицю eye (щоб у результаті вийшла матриця де цетнтральні діагональ все нулі).
 

Завдання 1:
Матриця одинична (eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Порівняння на наявність 1 у матриці:
[[ True False False]
 [False  True False]
 [False False  True]]

Завдання 2:
Матриця з одиниць:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Результат віднімання матриці eye від 

/var/folders/zs/2hgs2rgd08d2hcdh4l9r19dc0000gn/T/ipykernel_8443/2358189578.py:11: RuntimeWarning: divide by zero encountered in divide
  Ділення:\n {R / C}
/var/folders/zs/2hgs2rgd08d2hcdh4l9r19dc0000gn/T/ipykernel_8443/2358189578.py:14: RuntimeWarning: divide by zero encountered in divide
  Ділення на 0:\n {O / Z}


# Множення матриць
>  якщо маси яно не задати як матрицю, тоді операції будуть виконуавтись до кожного елемента.

In [49]:
A = np.array([ [1, 2, 3], [2, 2, 2], [3, 3, 3] ])
B = np.array([ [3, 2, 1], [1, 2, 3], [-1, -2, -3] ])
print(f"Маємо два масиви:\n {A} \n {B}")

R = A * B
print(f"Тут виконується поелементне множення:\n {R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n {R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n {R}")

Маємо два масиви:
 [[1 2 3]
 [2 2 2]
 [3 3 3]] 
 [[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
 [[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
 [[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей
> broadcasting - механізм який дозволяє вирівняти розмірність масивів для того щоб здійснити операцію над кожним його елементом. Масиви повинні бути співрозмірні, або один з вимірівв має бути 1 (рядок або стопець).

In [50]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)
> конкатенація (`concatenate`) - процес зчеплення двох і більше елементів (рядків, стовпців), у нашому випадку масивів які мають однакову форму shape;

> повторення (`tile`) - процес побудови масива шляхом повторення заданого елемента;

> зміна форми (`reshape`) або розмірності масива за умови що сумарна розмірність залишиться незмінною;

In [51]:
D = np.ones(3)
Z = np.zeros((3,1))
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))}")
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z))}
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з В {B} розмірністю {B.shape}:
{np.concatenate((B, D))}
Для конкатенації з С
{C}
де С має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можем виконати конкатенацію:
{np.concatenate((C, D.reshape((3,1))))}
При повторенні D {D} 2 рази для рядкі та 3 для стовпців будем мати:
{np.tile(D, (2, 3))}
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
""")



homework(f"""Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кількість рядкі та стовпців різна. Спробуйте виконати конкатенацію такого масиву з попереднім. Якщо розмірність масивів не спаівпадє використайте reshape.
Створіть декіль двовимірних масивів з сумарною розмірністю 12 та знайдіть всі можливі комбінції reshape. Наприклад, перша комбінація це рядок - {np.ones((1,12))}
""")

A = np.arange(6).reshape(2, 3)
B = np.arange(9).reshape(3, 3)

print(f"Конкатенація A і A по рядках:\n{np.concatenate((A, A), axis=0)}")
print(f"Конкатенація A і A по стовпцях:\n{np.concatenate((A, A), axis=1)}")

print(f"Повторення A два рази по рядках та 3 рази по стовпцях:\n{np.tile(A, (2, 3))}")

C = np.arange(4).reshape(2, 2) 
D = np.ones(2) 
D_reshaped = D.reshape(2, 1)

print(f"Конкатенація C та D (reshape для сумісності):\n{np.concatenate((C, D_reshaped), axis=1)}")

E = np.arange(12) 

print(f"Розмірність 1x12: {E.reshape(1, 12)}")
print(f"Розмірність 2x6: {E.reshape(2, 6)}")
print(f"Розмірність 3x4: {E.reshape(3, 4)}")
print(f"Розмірність 4x3: {E.reshape(4, 3)}")
print(f"Розмірність 6x2: {E.reshape(6, 2)}")
print(f"Розмірність 12x1: {E.reshape(12, 1)}")


При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.]")
При конкатенації стовпців маємо:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з В [1 2 3] розмірністю (3,):
[1. 2. 3. 1. 1. 1.]
Для конкатенації з С
[[1]
 [2]
 [3]]
де С має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можем виконати конкатенацію:
[[1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [1.]]
При повторенні D [1. 1. 1.] 2 рази для рядкі та 3 для стовпців будем мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Як бачимо конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: [1. 1. 1. 1. 1. 1.]
- повторення: [1. 1. 1. 1. 1. 1.]
Також можна перетворити двовимірний масив A розмірністю (3, 3) на рядок: [11 12 13 21 22 23 31 32 33] з розмірністю (9,)


>>>>> Створіть двохвимірний масив за допомогою arange та виконайте конкатенацію та повторення.
Створіть масив в якому кіль

# Трансформації масивів
> масии можуть бути трансформовані багатьма способами зміщюючи позиції рядкі або стопців;

> транспонація - заміна рядкі на стопці;

> функції `size` та `shape` - дозволяють визначити кількість елементів 

In [52]:
O = np.arange(6).reshape(3,2)
O_r = O.reshape((2,3))
O_f = O.flatten()
O_t = O.transpose()
O_fl = np.flip(O)
O_fa = np.flip(O, axis=1)

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")

homework("""
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
""")
import numpy as np

# 1. Створення вектора з 12 елементів
vector = np.arange(12)
print(f"Вектор з 12 елементів: {vector}")
print(f"Shape: {vector.shape}, Size: {vector.size}, Ndim: {np.ndim(vector)}")

# 2. Зміна розміру вектора на матрицю
matrix = vector.reshape(3, 4)
print(f"Матриця з розмірністю (3, 4): \n{matrix}")
print(f"Shape: {matrix.shape}, Size: {matrix.size}, Ndim: {np.ndim(matrix)}")

# 3. Транспонування матриці
transposed_matrix = matrix.T
print(f"Транспонована матриця: \n{transposed_matrix}")
print(f"Shape: {transposed_matrix.shape}, Size: {transposed_matrix.size}, Ndim: {np.ndim(transposed_matrix)}")

# 4. Обертання матриці
flipped_matrix = np.flip(matrix)
print(f"Обернена матриця: \n{flipped_matrix}")
print(f"Shape: {flipped_matrix.shape}, Size: {flipped_matrix.size}, Ndim: {np.ndim(flipped_matrix)}")

# 5. Перетворення багатовимірного масиву назад у вектор (стрічку)
flattened_matrix = flipped_matrix.flatten()
print(f"Перетворений у вектор: {flattened_matrix}")
print(f"Shape: {flattened_matrix.shape}, Size: {flattened_matrix.size}, Ndim: {np.ndim(flattened_matrix)}")

[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]


>>>>> 
- Створіть вектор з 12 елементів, визначте його shape, size та ndim;
- Змініть розмірніть перетворивши вектор у матрицю;
- Здійсніть транспонування отриманої матриці та оберніть її;
- Перетворіть отриманий багатовимірний масив назад у вектор (стрічку);
 

Вектор з 12 елементів: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,), Size: 12, Ndim: 1
Матриця з розмірністю (3, 4): 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4), Size: 1